version: '3.7'

networks:
  default:
    name: ${PROJECT_NAME}

volumes:
  pgdata:

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - .:/app:z
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    command: ['npm', 'run', 'start']
    env_file: ./.env.development
    environment:
      - DB_HOST=db
      - S3_HOST=s3
    networks:
      - default
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    command: -p ${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:z
    networks:
      - default

  admin:
    image: michalhosna/adminer
    ports:
      - ${ADMIN_PORT}:8080
    environment:
      ADMINER_DB: ${DB_NAME}
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: ${DB_PASSWORD}
      ADMINER_SERVER: db
      ADMINER_USERNAME: ${DB_USER}
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: ${API_NAME}
    networks:
      - default

  s3:
    image: localstack/localstack
    ports:
      - ${S3_PORT}:4566
    environment:
      - SERVICES=s3:4566
      - DEFAULT_REGION=${S3_REGION}
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./docker/s3:/docker-entrypoint-initaws.d
      - ./docker/s3/data:/tmp/localstack/data:z
