version: '3.7'

networks:
  network:
    name: ${API_NAME}

volumes:
  pgdata:

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - .:/app:z
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    command: ['npm', 'run', 'start']
    env_file: ./.env.development
    environment:
      - DB_HOST=db
    networks:
      - network
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    command: -p ${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    networks:
      - network

  admin:
    image: michalhosna/adminer
    ports:
      - ${ADMIN_PORT}:8080
    environment:
      ADMINER_DB: ${DB_NAME}
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: ${DB_PASSWORD}
      ADMINER_SERVER: db
      ADMINER_USERNAME: ${DB_USER}
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: ${API_NAME}
    networks:
      - network
