export enum ExceptionError {
  BAD_REQUEST_EMAIL_ALREADY_EXISTS = 'BAD_REQUEST_EMAIL_ALREADY_EXISTS',
  BAD_REQUEST_INVALID_EMAIL = 'BAD_REQUEST_INVALID_EMAIL',
  BAD_REQUEST_INVALID_PASSWORD = 'BAD_REQUEST_INVALID_PASSWORD',
  BAD_REQUEST_INVALID_FILES = 'BAD_REQUEST_INVALID_FILES',
  BAD_REQUEST_EMAIL_ALREADY_CONFIRMED = 'BAD_REQUEST_EMAIL_ALREADY_CONFIRMED',
  BAD_REQUEST_NEW_PASSWORD_MUST_BE_DIFFERENT = 'BAD_REQUEST_NEW_PASSWORD_MUST_BE_DIFFERENT',
  FORBIDDEN_MUST_BE_OWNER = 'FORBIDDEN_MUST_BE_OWNER',
  FORBIDDEN_NOT_A_CONFIRMED_ACCOUNT = 'FORBIDDEN_NOT_A_CONFIRMED_ACCOUNT',
}
